./word-dl.sh $1 "baby shark"
./word-dl.sh $1 "mommy shark"
./word-dl.sh $1 "daddy shark"
./word-dl.sh $1 "grandma shark"
./word-dl.sh $1 "grandpa shark"
./word-dl.sh $1 "baby"
./word-dl.sh $1 "mommy"
./word-dl.sh $1 "daddy"
./word-dl.sh $1 "grandma"
./word-dl.sh $1 "grandpa"
v./word-dl.sh $1 "shark"
./word-dl.sh $1 "let\'s go hunt"
./word-dl.sh $1 "run away"
./word-dl.sh $1 "safe at last"
./word-dl.sh $1 "It\'s the end"
./word-dl.sh $1 "let\'s"
./word-dl.sh $1 "go"
./word-dl.sh $1 "hunt"
./word-dl.sh $1 "run"
./word-dl.sh $1 "away"
./word-dl.sh $1 "safe"
./word-dl.sh $1 "at last"
./word-dl.sh $1 "at"
./word-dl.sh $1 "last"
./word-dl.sh $1 "the end"
./word-dl.sh $1 "the"
./word-dl.sh $1 "end"
./word-dl.sh $1 "doo doo"
./word-dl.sh $1 "do do do"
./word-dl.sh $1 "do do"
