./word-dl.sh $1 "the"
./word-dl.sh $1 "Snow"
./word-dl.sh $1 "glow"
./word-dl.sh $1 "white"
./word-dl.sh $1 "on the"
./word-dl.sh $1 "mountain"
./word-dl.sh $1 "tonight"
./word-dl.sh $1 "Not"
./word-dl.sh $1 "footprint"
./word-dl.sh $1 "to be"
./word-dl.sh $1 "you seen"
./word-dl.sh $1 " A "
./word-dl.sh $1 "kingdom"
./word-dl.sh $1 "of"
./word-dl.sh $1 "isolation"
./word-dl.sh $1 "And"
./word-dl.sh $1 "it"
./word-dl.sh $1 "looks like"
./word-dl.sh $1 "Im"
./word-dl.sh $1 "queen"
./word-dl.sh $1 "wind"
./word-dl.sh $1 "is"
./word-dl.sh $1 "howling"
./word-dl.sh $1 "like"
./word-dl.sh $1 "this"
./word-dl.sh $1 "swirling"
./word-dl.sh $1 "storm"
./word-dl.sh $1 "inside"
./word-dl.sh $1 "Couldnt"
./word-dl.sh $1 "keep"
./word-dl.sh $1 "in"
./word-dl.sh $1 "heaven"
./word-dl.sh $1 "knows"
./word-dl.sh $1 "Ive"
./word-dl.sh $1 "tried"
./word-dl.sh $1 "Dont"
./word-dl.sh $1 "let"
./word-dl.sh $1 "them"
./word-dl.sh $1 "see"
./word-dl.sh $1 " Be "
./word-dl.sh $1 "good"
./word-dl.sh $1 "girl"
./word-dl.sh $1 "you"
./word-dl.sh $1 "always"
./word-dl.sh $1 "have"
./word-dl.sh $1 "Conceal"
./word-dl.sh $1 "dont"
./word-dl.sh $1 "feel"
./word-dl.sh $1 "dont let"
./word-dl.sh $1 "them know"
./word-dl.sh $1 "Well"
./word-dl.sh $1 "right now"
./word-dl.sh $1 "they"
./word-dl.sh $1 "know"
./word-dl.sh $1 "Let it go"
./word-dl.sh $1 "go out"
./word-dl.sh $1 "I cant"
./word-dl.sh $1 "hold"
./word-dl.sh $1 "it back"
./word-dl.sh $1 "back"
./word-dl.sh $1 "anymore"
./word-dl.sh $1 "Turn"
./word-dl.sh $1 "go away"
./word-dl.sh $1 "and"
./word-dl.sh $1 "slam"
./word-dl.sh $1 "the door"
./word-dl.sh $1 "I"
./word-dl.sh $1 "care"
./word-dl.sh $1 "what"
./word-dl.sh $1 "theyre"
./word-dl.sh $1 "going"
./word-dl.sh $1 "to"
./word-dl.sh $1 "say"
./word-dl.sh $1 "Let"
./word-dl.sh $1 "the storm"
./word-dl.sh $1 " rage "
./word-dl.sh $1 " on "
./word-dl.sh $1 "The"
./word-dl.sh $1 "its cold"
./word-dl.sh $1 "never"
./word-dl.sh $1 "bothered"
./word-dl.sh $1 " me "
./word-dl.sh $1 "anyway"
