# ./word-dl.sh $1 "eye"
./word-dl.sh $1 "play"
./word-dl.sh $1 "Pokemon"
./word-dl.sh $1 " go "
# ./word-dl.sh $1 "everyday"
./word-dl.sh $1 "when"
# ./word-dl.sh $1 "I"
# ./word-dl.sh $1 "wake up"
./word-dl.sh $1 "I'm"
./word-dl.sh $1 "grabbing"
./word-dl.sh $1 "my phone"
./word-dl.sh $1 "I"
./word-dl.sh $1 "wanna"
# ./word-dl.sh $1 "catch"
# ./word-dl.sh $1 "them"
./word-dl.sh $1 "all"
./word-dl.sh $1 "Poke"
# ./word-dl.sh $1 "see"
# ./word-dl.sh $1 "on"
