./word-dl.sh $1 "want"
./word-dl.sh $1 "to "
./word-dl.sh $1 " be "
./word-dl.sh $1 " the "
./word-dl.sh $1 " very "
./word-dl.sh $1 "best "
./word-dl.sh $1 "Like "
./word-dl.sh $1 "know"
./word-dl.sh $1 "one"
./word-dl.sh $1 "ever "
./word-dl.sh $1 "was "
./word-dl.sh $1 "Two "
./word-dl.sh $1 "catching "
./word-dl.sh $1 "them "
./word-dl.sh $1 " is "
./word-dl.sh $1 " my"
./word-dl.sh $1 "real "
./word-dl.sh $1 " testing "
./word-dl.sh $1 "train "
./word-dl.sh $1 "them "
./word-dl.sh $1 "cause "
./word-dl.sh $1 "I will "
./word-dl.sh $1 "traveling"
./word-dl.sh $1 " across "
./word-dl.sh $1 "landed"
./word-dl.sh $1 " Searching "
./word-dl.sh $1 "far "
./word-dl.sh $1 "and "
./word-dl.sh $1 "wide "
./word-dl.sh $1 " Pokemon "
./word-dl.sh $1 "understand "
./word-dl.sh $1 "power "
./word-dl.sh $1 " that "
./word-dl.sh $1 "inside "
./word-dl.sh $1 "Its "
./word-dl.sh $1 "you "
./word-dl.sh $1 " me "
./word-dl.sh $1 "eye "
./word-dl.sh $1 "know "
./word-dl.sh $1 "destiny "
# ./word-dl.sh $1 "Oh "
# ./word-dl.sh $1 "Ohh "
# ./word-dl.sh $1 "Ohhh "
# ./word-dl.sh $1 "Ohhhh "
# ./word-dl.sh $1 "Oo "
# ./word-dl.sh $1 "Ooo "
./word-dl.sh $1 "youre "
./word-dl.sh $1 "best "
./word-dl.sh $1 "friend "
./word-dl.sh $1 "In "
./word-dl.sh $1 "A  "
./word-dl.sh $1 "world "
./word-dl.sh $1 "we "
./word-dl.sh $1 "must "
./word-dl.sh $1 "defend "
./word-dl.sh $1 "got"
./word-dl.sh $1 "got to"
./word-dl.sh $1 "all "
./word-dl.sh $1 "heart "
./word-dl.sh $1 " so "
./word-dl.sh $1 "true "
./word-dl.sh $1 " our "
./word-dl.sh $1 "courage "
./word-dl.sh $1 "will"
./word-dl.sh $1 "pull "
./word-dl.sh $1 "let us"
./word-dl.sh $1 "through "
./word-dl.sh $1 "I will"
# ./word-dl.sh $1 " Po"
# ./word-dl.sh $1 " key "
# ./word-dl.sh $1 " ma "
