./word-dl.sh radio " no."
./word-dl.sh radio " one."
./word-dl.sh radio "catch them"
./word-dl.sh radio "is my"
./word-dl.sh radio "real test"
./word-dl.sh radio "train them"
./word-dl.sh radio "my cause"
./word-dl.sh radio "searching"
./word-dl.sh radio "far and wide"
./word-dl.sh radio " teach."
./word-dl.sh radio "to understand"
./word-dl.sh radio "the power"
./word-dl.sh radio " thats "
./word-dl.sh radio " inside."
./word-dl.sh radio " gotta "
./word-dl.sh radio "you and me"
./word-dl.sh radio "I know."
./word-dl.sh radio "its my"
./word-dl.sh radio "destiny"
./word-dl.sh radio "oh"
./word-dl.sh radio "my best friend"
./word-dl.sh radio "in a world"
./word-dl.sh radio "we must"
./word-dl.sh radio "defend"
./word-dl.sh radio "heart"
./word-dl.sh radio "so true"
./word-dl.sh radio "our courage"
./word-dl.sh radio "will pull"
./word-dl.sh radio "us through"
./word-dl.sh radio "teach me"
./word-dl.sh radio "teach you"
./word-dl.sh radio "catch."