./word-dl.sh $1 "Alabama"
./word-dl.sh $1 "Alaska"
./word-dl.sh $1 "Arizona"
./word-dl.sh $1 "Arkansas"
./word-dl.sh $1 "California"
./word-dl.sh $1 "Colorado"
./word-dl.sh $1 "Connecticut"
./word-dl.sh $1 "Delaware"
./word-dl.sh $1 "Florida"
./word-dl.sh $1 "Georgia"
./word-dl.sh $1 "Hawaii"
./word-dl.sh $1 "Idaho"
./word-dl.sh $1 "Illinois"
./word-dl.sh $1 "Indiana"
./word-dl.sh $1 "Iowa"
./word-dl.sh $1 "Kansas"
./word-dl.sh $1 "Kentucky"
./word-dl.sh $1 "Louisiana"
./word-dl.sh $1 "Maine"
./word-dl.sh $1 "Maryland"
./word-dl.sh $1 "Massachusetts"
./word-dl.sh $1 "Michigan"
./word-dl.sh $1 "Minnesota"
./word-dl.sh $1 "Mississippi"
./word-dl.sh $1 "Missouri"
./word-dl.sh $1 "Montana"
./word-dl.sh $1 "Nebraska"
./word-dl.sh $1 "Nevada"
./word-dl.sh $1 "New Hampshire"
./word-dl.sh $1 "New Jersey"
./word-dl.sh $1 "New Mexico"
./word-dl.sh $1 "New York"
./word-dl.sh $1 "North Carolina"
./word-dl.sh $1 "North Dakota"
./word-dl.sh $1 "Ohio"
./word-dl.sh $1 "Oklahoma"
./word-dl.sh $1 "Oregon"
./word-dl.sh $1 "Pennsylvania"
./word-dl.sh $1 "Rhode Island"
./word-dl.sh $1 "South Carolina"
./word-dl.sh $1 "South Dakota"
./word-dl.sh $1 "Tennessee"
./word-dl.sh $1 "Texas"
./word-dl.sh $1 "Utah"
./word-dl.sh $1 "Vermont"
./word-dl.sh $1 "Virginia"
./word-dl.sh $1 "Washington"
./word-dl.sh $1 "West Virginia"
./word-dl.sh $1 "Wisconsin"
./word-dl.sh $1 "Wyoming"
